// <auto-generated />
namespace AD_Team10.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.0")]
    public sealed partial class Snap3 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Snap3));
        
        string IMigrationMetadata.Id
        {
            get { return "202002071447582_Snap3"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
